name: CI/CD Docker SpringBoot

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2. JDK 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 빌드
      - name: Build with Gradle
        run: |
          chmod +x gradlew   
          ./gradlew build

      # 4. Docker 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Docker 이미지 빌드 및 푸시
      - name: Docker build & push to Docker hub
        run: |
          sudo chmod 666 /var/run/docker.sock

      # 6. EC2 접속 및 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_SERVER_HOST }}
          username: ${{ secrets.EC2_SERVER_USER }}
          key: ${{ secrets.EC2_SERVER_KEY }}
          script: |
            cd /home/ubuntu/36-COLLABORATION-SERVER-HOLIX
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t ${{ secrets.DOCKER_USERNAME }}/holix-server .
            docker stop holix-server || true
            docker rm holix-server || true
            docker run -d -p 8080:8080 --name holix-server ${{ secrets.DOCKER_USERNAME }}/holix-server
